### ISSUE TITLE
WalletConnect 로 지갑 연결 시도시 z-index 문제

### ISSUE THREAD

**Issue by livetOwO** [DeSpread/3ridge-frontend#223]
재현 방법:
(지갑 연결 해제 상태)
1. 우상단 "지갑 연결" 버튼 클릭
2. 아무 네트워크 선택
3. WalletConnect 선택
4. WalletConnect 모달이 뒤로 뜨는 문제 발생
<img width="585" alt="image" src="https://github.com/DeSpread/3ridge-frontend/assets/63547636/6d1d5112-f2ee-44de-882c-d516fe14ff04">

**Comment by dev-minsu** [comment]
https://github.com/DeSpread/3ridge-frontend/pull/227에서 수정 중
