### ISSUE TITLE
반응형 레이아웃(작은 상태) 에서 우상단 토스트 버튼 호버 시 불투명 요소 노출 이슈

### ISSUE THREAD

**Issue by livetOwO** [DeSpread/3ridge-frontend#224]
재현방법:
1. 상단 메뉴에 토스트 버튼이 노출될 정도로 브라우저를 줄인다
2. 우상단 토스트 버튼에 마우스를 올린다
3. 불투명 요소가 버튼을 가린다
<img width="594" alt="image" src="https://github.com/DeSpread/3ridge-frontend/assets/63547636/c6e56c15-66a7-40ee-8384-5aebc951be35">

**Comment by dev-minsu** [comment]
마이너한 이슈로 보입니다
시간되실때 토스트 버튼에 hover 관련 style을 추가해주시면 좋을것 같습니다
